version: '3.8'

services:
  
  back-end:
    image: node:lts-alpine
    working_dir: /application/trocaTroca/api
    volumes:
      - ./trocaTroca/api:/application/trocaTroca/api
    ports:
      - 3000:3000
    entrypoint: sh init.sh
    command: npm start

  front-end:
    image: node:lts-alpine
    working_dir: /application/trocaTroca/front-end/app
    volumes:
      - ./trocaTroca/front-end:/application/trocaTroca/front-end
    ports:
      - 5173:5173
    entrypoint: sh ../init.sh
    command: npm run dev -- --host 0.0.0.0
    restart: always
